[1주차] 기본/도전 과제 제출
IN-SOPT-SERVER/SeungBin pull request #2
Opened 2022-10-02 07:13 UTC by csb9427

### SERVER PR

<br />

## 🐕 과제 구현 명세

- 기본 과제랑 도전 과제를 했습니다. 
- 도전 과제에서는 멤버와 디너의 인터페이스를 만들고 랜덤 멤버1, 랜덤 멤버2 변수에 이름을 저장한 후 디너멤버에 배열로 저장해 출력하도록 했습니다.

<br />

## 🐥 이런 점이 새로웠어요 / 어려웠어요

- 세미나 너무 유익하고 좋아요~~

2022-10-04 07:14 UTC, devkwonsehoon requested changes

2022-10-04 07:14 UTC, devkwonsehoon commented on 1차 세미나/work.ts
> +];
member 인터페이스는 생성했으나 members 배열에 타입 지정을 하지 않으셨네요.
타입 지정 해주세요!

2022-10-04 07:14 UTC, devkwonsehoon commented on 1차 세미나/work.ts
> +interface member {
```suggestion
interface Member {
```
인터페이스의 이름은 PascalCase, 프로퍼티 이름은 camelCase 로 하시는 것을 추천드립니다.

Typescript 에서 Interface 의 네이밍 컨벤션은 이 [링크](https://dirask.com/posts/TypeScript-interface-naming-convention-x1RwqD)에서 더 잘 확인하실 수 있습니다.

2022-10-04 20:10 UTC, Soyewon approved these changes
파트장님 댓글이랑 같이 보고 한 수 배워갑니다,,,

2022-10-04 20:11 UTC, Soyewon approved these changes

2022-10-05 01:04 UTC, csb9427 commented on 1차 세미나/work.ts
> +];
앗 감사합니다!!

2022-10-05 01:04 UTC, csb9427 commented on 1차 세미나/work.ts
> +interface member {
좋은 정보 감사합니다! 바로 수정하겠습니다!

2022-10-05 17:25 UTC, yeseul106 approved these changes
깔꼼한 코드 잘 보고 갑니다아~~

2022-10-05 17:25 UTC, yeseul106 commented on 1차 세미나/random.ts
> +  shuffle(array): Member[] {
interface에서 타입 정의해줬는데 다시 여기서도 타입을 지정 해줘야 되는건가 ?? 나 진짜 ts랑 안 친해서 궁금해서 물어보는거야..🥹

2022-10-06 02:24 UTC, csb9427 commented on 1차 세미나/random.ts
> +  shuffle(array): Member[] {
아뇨 객체가 대입될 인터페이스에 타입이 있어서 상관은 없습니다 있어도 되고 없어도 되고... 이런 코드 리뷰 너무 좋습니다!!

2022-10-15 05:09 UTC, merged